### ISSUE TITLE
Test Client support for logout

### ISSUE THREAD

**Issue by ivorbosloper** [Bouke/django-user-sessions#29]
I'm using `user_sessions.utils.tests.Client` for my own webtests, but logout() raises an error.

A minimal testcase would be:

```
class ClientTest(TestCase):
    def test_login_logout(self):
        client = Client()
        User.objects.create_user('bouke', '', 'secret')
        assert client.login(username='bouke', password='secret')
        client.logout()
```

Result:

```
======================================================================
ERROR: test_login_logout (tests.tests.ClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "django-user-sessions/tests/tests.py", line 281, in test_login_logout
    client.logout()
  File "django/test/client.py", line 556, in logout
    session = import_module(settings.SESSION_ENGINE).SessionStore()
TypeError: __init__() takes at least 3 arguments (1 given)
```

**Comment by Bouke** [comment]
Merged in #30, thanks!
